server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1   
  
spring:
  application:
    name: spring-cloud-zuul
zuul:
  routes:
    spring-cloud-uaa:
      path: /uaa/**
      serviceId: spring-cloud-uaa
      strip-prefix: false
    customer-management:
      path: /customer/**
      serviceId: customer-management
      strip-prefix: false
    product-management:
      path: /product/**
      serviceId: product-management
      strip-prefix: false
    order-management:
      path: /order/**
      service-id: order-management
      strip-prefix: false
    core-management:
      path: /core/**
      service-id: core-management
      strip-prefix: false
      