server:
  port: 8040
  servlet:
    context-path: /uaa

spring:
  application:
    name: spring-cloud-uaa

eureka:
  client:
    serviceUrl:
      defaultZone: http://129.204.105.83:8000/eureka/
  instance:
    prefer-ip-address: true