server:
  port: 8040
  servlet:
    context-path: /uaa

spring:
  application:
    name: spring-cloud-uaa
  datasource:
    url: jdbc:mysql://47.96.224.108:3306/customerdb?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://129.204.105.83:8000/eureka/
  instance:
    prefer-ip-address: true

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1